version: '3'
services:
  db:
    image: mariadb:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
  backend:
    build: ./backend
    ports:
      - "8090:8090"
  infomatics:
    build: ./informational-analytics
    ports:
      - "8585:8585"
