
export const BASE_URL = 'http://0.0.0.0:8090'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const SIGN_UP = 'SIGN_UP'

export const NEW_RECEIPT_DATA = 'NEW_RECEIPT_DATA';
export const SET_RECEIPT = 'SET_RECEIPT';
export const SET_RECEIPT_HISTORY = 'SET_RECEIPT_HISTORY';
export const SET_RECEIPT_ITEM = 'SET_RECEIPT_ITEM';

export const REMOVE_RECEIPT = 'REMOVE_RECEIPT';




// grocery list
export const ADD_TO_DEFAULT = 'ADD_TO_DEFAULT'
export const REMOVE_FROM_DEFAULT = 'REMOVE_FROM_DEFAULT'
export const UPDATE_DEFAULT_ITEM = 'UPDATE_DEFAULT_ITEM'

export const SET_SUGGESTED_ITEM_LIST = 'SET_SUGGESTED_ITEM_LIST';
export const SET_RECOMMENDED_GROCERY_LIST = 'SET_RECOMMENDED_GROCERY_LIST';
