DROP DATABASE IF EXISTS FOOD_WASTE_CONSUMER_DB;

CREATE DATABASE FOOD_WASTE_CONSUMER_DB;

USE FOOD_WASTE_CONSUMER_DB;

DROP TABLE IF EXISTS USER_PROFILE;

CREATE TABLE IF NOT EXISTS USER_PROFILE
(USER_ID VARCHAR(128) primary key, /*Login User Name*/
 USER_NM varchar(128) , /*Name of User*/
 USER_AGE integer,
 PASSWORD VARCHAR(128),
 /*FAMILY_MBR_ID bigint,*/
 FAMILY_SIZE integer,
 NUM_ADULTS integer,
 NUM_KIDS integer,
 ANNUAL_HOUSEHOLD_INCOME VARCHAR(200), /* Range */
 SHOP_TRIP_FREQ INTEGER
  );

/*
DROP TABLE IF EXISTS USER_SECURE_INFO;

CREATE TABLE IF NOT EXISTS USER_SECURE_INFO
(USER_ID VARCHAR(128) primary key,
 PASSWORD VARCHAR(128)
);
*/

/*DROP TABLE IF EXISTS USER_FAMILY;

CREATE TABLE IF NOT EXISTS USER_FAMILY
(USER_ID VARCHAR(128),
 FAMILY_MBR_ID bigint ,
 FAMILY_MBR_NM varchar(128) ,
 FAMILY_MBR_AGE integer,
 FAMILY_MEMBER_TYPE  VARCHAR(20),
 CONSTRAINT user_family_pk PRIMARY KEY (USER_ID, FAMILY_MBR_ID)
  );*/


DROP TABLE IF EXISTS USER_GROCERY_RECEIPT;

CREATE TABLE IF NOT EXISTS USER_GROCERY_RECEIPT
(USER_ID VARCHAR(128), /*Login User Name*/
 RECEIPT_ID bigint,   /* System Generated ID - Hash Value from Receipt */
 RECEIPT_UPLOAD_DT date,
 ITEM_ID bigint, /* UPC Code */
 ITEM_NAME VARCHAR(100), /* Name from Receipt */
 ITEM_QTY_PRCH decimal unsigned,
 ITEM_UNITS varchar(20)	,
 ITEM_TOTAL_PRICE decimal unsigned, /* Price in Dollars */
 ITEM_CATEGORY varchar(30), /* OCR Closest Category */
 CONSTRAINT groceries_pk PRIMARY KEY (USER_ID, RECEIPT_ID , UPLOAD_DT)
 );



/*
DROP TABLE IF EXISTS USER_GROCERY_ITEM_LKP;

CREATE TABLE IF NOT EXISTS USER_GROCERY_ITEM_LKP
(ITEM_ID bigint primary key,
ITEM_NAME varchar(100) );
*/

DROP TABLE IF EXISTS USER_GROCERY_ITEM_WASTE_ACTUAL;

CREATE TABLE IF NOT EXISTS USER_GROCERY_ITEM_WASTE_ACTUAL
(USER_ID VARCHAR(128),
 RECEIPT_ID bigint,
 RECEIPT_UPLOAD_DT date,
 WASTE_DATA_ENTRY_DT date,
 ITEM_ID bigint,varchar(100),
 ITEM_NAME varchar(100),
 ITEM_CATEGORY varchar(30),
 ITEM_TOTAL_PRICE decimal unsigned,
 WASTE_AMT decimal unsigned,
 WASTE_UNITS varchar(30),
 CONSTRAINT grocery_waste_pk PRIMARY KEY (USER_ID, RECEIPT_ID , DATA_ENTRY_DT, ITEM_ID)
 );

DROP TABLE IF EXISTS USER_GROCERY_ITEM_WASTE_PRED;

CREATE TABLE IF NOT EXISTS USER_GROCERY_ITEM_WASTE_PRED
(USER_ID VARCHAR(128),
 SHOPPING_TRIP_ID bigint, /*System Generated - Autoincrement*/
 RECOMMENDATION_CATEGORY varchar(100), /* Values - Recommended or Suggested */
 MODEL_RUN_DT date,
 ITEM_ID bigint,
 ITEM_NAME varchar(100),
 ITEM_CATEGORY varchar(30),
 PRED_WASTE_AMT decimal unsigned,
 PRED_WASTE_UNITS varchar(30),
 RECOMMENDED_QTY bigint,
 RECOMMENDED_QTY_UNITS varchar(30),
 MODEL_TYPE varchar(20),
 CONSTRAINT grocery_waste_pred_pk PRIMARY KEY (USER_ID, SHOPPING_TRIP_ID , MODEL_RUN_DT, ITEM_ID)
 );



DROP TABLE IF EXISTS USER_RECO_GROCERY_EDITS_STG;

CREATE TABLE IF NOT EXISTS USER_RECO_GROCERY_EDITS_STG
(USER_ID VARCHAR(128),
 SHOPPING_TRIP_ID bigint,
 RECOMMENDATION_CATEGORY varchar(100), /* Values - Recommended or Suggested */
 EDIT_DT date,
 ITEM_ID bigint,
 ITEM_NAME varchar(100),
 ITEM_CATEGORY varchar(30),
 RECOMMENDED_QTY bigint,
 ITEM_UNITS varchar(30),
 EDITED_QTY bigint,
 CONSTRAINT grocery_waste_pred_pk PRIMARY KEY (USER_ID, SHOPPING_TRIP_ID , EDIT_DT, ITEM_ID)
 );


DROP TABLE IF EXISTS USER_RECO_GROCERY_EDITS_HIST;

CREATE TABLE IF NOT EXISTS USER_RECO_GROCERY_EDITS_HIST
(USER_ID VARCHAR(128),
 SHOPPING_TRIP_ID bigint,
 RECOMMENDATION_CATEGORY varchar(100), /* Values - Recommended or Suggested */
 EDIT_DT date,
 ITEM_ID bigint,
 ITEM_NAME varchar(100),
 ITEM_CATEGORY varchar(30),
 RECOMMENDED_QTY bigint,
 ITEM_UNITS varchar(30),
 EDITED_QTY bigint,
 CONSTRAINT grocery_waste_pred_pk PRIMARY KEY (USER_ID, SHOPPING_TRIP_ID , EDIT_DT, ITEM_ID)
 );




DROP TABLE IF EXISTS USER_GROCERY_ITEM_PRCH_FREQ;

CREATE TABLE IF NOT EXISTS USER_GROCERY_ITEM_PRCH_FREQ
(USER_ID VARCHAR(128),
 ITEM_ID bigint,
 FRQ_PRCH_EVER bigint,
 FRQ_PRCH_LAST3_TRIPS integer,
 CONSTRAINT grocery_prch_freq_pk PRIMARY KEY (USER_ID, ITEM_ID)
 );
