DROP DATABASE IF EXISTS FOOD_WASTE_CONSUMER_DB;

CREATE DATABASE FOOD_WASTE_CONSUMER_DB;

USE FOOD_WASTE_CONSUMER_DB;

DROP TABLE IF EXISTS USER_PROFILE;

CREATE TABLE IF NOT EXISTS USER_PROFILE
(USER_ID VARCHAR(128) primary key, /*Login User Name*/
 USER_NM varchar(128) , /*Name of User*/
 USER_AGE integer,
 PASSWORD VARCHAR(128),
 FAMILY_SIZE integer,
 NUM_ADULTS integer,
 NUM_KIDS integer,
 ANNUAL_HOUSEHOLD_INCOME integer, /* Range */
 SHOP_TRIP_FREQ integer
);

DROP TABLE IF EXISTS USER_GROCERY_RECEIPT;

CREATE TABLE IF NOT EXISTS USER_GROCERY_RECEIPT
(USER_ID VARCHAR(128), /*Login User Name*/
 RECEIPT_ID bigint,   /* System Generated ID - Hash Value from Receipt */
 RECEIPT_UPLOAD_DT bigint,
 ITEM_ID bigint, /* UPC Code */
 ITEM_NAME VARCHAR(100), /* Name from Receipt */
 ITEM_QTY_PRCH decimal unsigned,
 ITEM_UNITS varchar(20)	,
 ITEM_TOTAL_PRICE decimal unsigned, /* Price in Dollars */
 ITEM_CATEGORY varchar(100), /* OCR Closest Category */
 CONSTRAINT groceries_pk PRIMARY KEY (USER_ID, RECEIPT_ID, ITEM_ID)
 );


DROP TABLE IF EXISTS USER_GROCERY_ITEM_WASTE_ACTUAL;

CREATE TABLE IF NOT EXISTS USER_GROCERY_ITEM_WASTE_ACTUAL
(USER_ID varchar(128),
 RECEIPT_ID bigint,
 WASTE_DATA_ENTRY_DT varchar(30),
 ITEM_ID varchar(100),
 ITEM_NAME varchar(100),
 ITEM_CATEGORY varchar(30),
 ITEM_SIZE decimal unsigned,
 ITEM_TOTAL_PRICE decimal unsigned,
 WASTE_AMT decimal unsigned,
 ITEM_UNITS  varchar(30),
 CONSTRAINT grocery_waste_pk PRIMARY KEY (USER_ID, RECEIPT_ID, ITEM_ID)
 );

DROP TABLE IF EXISTS USER_GROCERY_ITEM_WASTE_PRED;

CREATE TABLE IF NOT EXISTS USER_GROCERY_ITEM_WASTE_PRED
(USER_ID VARCHAR(128), /*Login User Name*/
 RECEIPT_ID bigint,   /* System Generated ID - Hash Value from Receipt */
 RECEIPT_UPLOAD_DT bigint,
 ITEM_ID bigint, /* UPC Code */
 ITEM_NAME VARCHAR(100), /* Name from Receipt */
 ITEM_QTY_PRCH decimal unsigned,
 ITEM_UNITS varchar(20)	,
 ITEM_TOTAL_PRICE decimal unsigned, /* Price in Dollars */
 ITEM_CATEGORY varchar(100), /* OCR Closest Category */
 ITEM_CLASS VARCHAR(30),
 ITEM_SIZE decimal unsigned,
 SHOPPING_DATE bigint,
 ITEM_TOTAL_SIZE decimal unsigned,
 FAMILY_SIZE integer,
 PER_CAPITA_SIZE decimal unsigned,
 PER_CAPITA_SIZE_TRIP decimal unsigned,
 PREVIOUS_SHOP_DATE bigint,
 PREVIOUS_SHOP_SIZE bigint,
 ITEM_SIZE_AVG decimal unsigned,
 ITEM_SIZE_STDEV decimal unsigned,
 ITEM_SIZE_Z decimal unsigned,
 ITEM_SIZE_ALL_AVG decimal unsigned,
 ITEM_SIZE_ALL_STDEV decimal unsigned,
 ITEM_SIZE_ALL_Z decimal unsigned,
 ITEM_DURATION decimal unsigned,
 TIME_LOSS_COUNTER decimal unsigned,
 TIME_LOSS bigint,
 TRIP_SIZE_AVG decimal unsigned,
 TRIP_SIZE_STDEV decimal unsigned,
 DAYS_BETWEEN_AVG decimal unsigned,
 DAYS_BETWEEN_STDEV decimal unsigned,
 PREV_SIZE_Z decimal unsigned,
 PREV_DATE_Z decimal unsigned,
 PREV_Z decimal unsigned,
 SHOPPING_RANK bigint,
 WASTE_AMT decimal unsigned,
 CONSTRAINT groceries_pk PRIMARY KEY (USER_ID, RECEIPT_ID, ITEM_ID)
 );



DROP TABLE IF EXISTS USER_RECO_GROCERY_EDITS_STG;

CREATE TABLE IF NOT EXISTS USER_RECO_GROCERY_EDITS_STG
(USER_ID VARCHAR(128),
 SHOPPING_TRIP_ID bigint,
 RECOMMENDATION_CATEGORY varchar(100), /* Values - Recommended or Suggested */
 EDIT_DT date,
 ITEM_ID bigint,
 ITEM_NAME varchar(100),
 ITEM_CATEGORY varchar(30),
 RECOMMENDED_QTY bigint,
 ITEM_UNITS varchar(30),
 EDITED_QTY bigint,
 CONSTRAINT grocery_waste_pred_pk PRIMARY KEY (USER_ID, SHOPPING_TRIP_ID , EDIT_DT, ITEM_ID)
 );


DROP TABLE IF EXISTS USER_RECO_GROCERY_EDITS_HIST;

CREATE TABLE IF NOT EXISTS USER_RECO_GROCERY_EDITS_HIST
(USER_ID VARCHAR(128),
 SHOPPING_TRIP_ID bigint,
 RECOMMENDATION_CATEGORY varchar(100), /* Values - Recommended or Suggested */
 EDIT_DT date,
 ITEM_ID bigint,
 ITEM_NAME varchar(100),
 ITEM_CATEGORY varchar(30),
 RECOMMENDED_QTY bigint,
 ITEM_UNITS varchar(30),
 EDITED_QTY bigint,
 CONSTRAINT grocery_waste_pred_pk PRIMARY KEY (USER_ID, SHOPPING_TRIP_ID , EDIT_DT, ITEM_ID)
 );




DROP TABLE IF EXISTS USER_GROCERY_ITEM_PRCH_FREQ;

CREATE TABLE IF NOT EXISTS USER_GROCERY_ITEM_PRCH_FREQ
(USER_ID VARCHAR(128),
 ITEM_ID bigint,
 FRQ_PRCH_EVER bigint,
 FRQ_PRCH_LAST3_TRIPS integer,
 CONSTRAINT grocery_prch_freq_pk PRIMARY KEY (USER_ID, ITEM_ID)
 );



DROP TABLE IF EXISTS USER_GROCERY_ITEM_LOOKUP;

CREATE TABLE IF NOT EXISTS USER_GROCERY_ITEM_LOOKUP
(ITEM_ID bigint primary key,
 ITEM_NAME VARCHAR(100),
 ITEM_CATEGORY VARCHAR(30),
 ITEM_CLASS VARCHAR(30),
 ITEM_SIZE decimal unsigned,
 ITEM_UNITS varchar(30),
 ITEM_DURATION decimal unsigned,
 CONSTRAINT items_pk PRIMARY KEY (ITEM_ID)
 );



DROP TABLE IF EXISTS SAMPLE_RECEIPTS;

CREATE TABLE IF NOT EXISTS SAMPLE_RECEIPTS
(USER_ID VARCHAR(128),
 ITEM_ID bigint,
 ITEM_SIZE decimal unsigned,
 ITEM_QTY_PRCH bigint,
 SHOPPING_DATE bigint,
 RECEIPT_ID bigint,
 ITEM_TOTAL_PRICE decimal unsigned,
 CONSTRAINT groceries_PK PRIMARY KEY (USER_ID, RECEIPT_ID, ITEM_ID)
 );


DROP TABLE IF EXISTS MODEL_PARAMETERS;

CREATE TABLE IF NOT EXISTS MODEL_PARAMETERS
(VARIABLE VARCHAR(128) primary key,
 COEFFICIENTS decimal unsigned
);


 --
 -- INSERT INTO USER_PROFILE (
 --   USER_ID,
 --   USER_NM,
 --   PASSWORD,
 --   USER_AGE,
 --   FAMILY_SIZE,
 --   NUM_ADULTS,
 --   NUM_KIDS,
 --   ANNUAL_HOUSEHOLD_INCOME,
 --   SHOP_TRIP_FREQ
 -- )
 -- VALUES ("bob", "Bob McBob","bobpass", 30, 3, 2, 1, 1000000, 5);
 -- INSERT INTO USER_PROFILE (
 --   USER_ID,
 --   USER_NM,
 --   PASSWORD,
 --   USER_AGE,
 --   FAMILY_SIZE,
 --   NUM_ADULTS,
 --   NUM_KIDS,
 --   ANNUAL_HOUSEHOLD_INCOME,
 --   SHOP_TRIP_FREQ
 -- )
 -- VALUES ("jane", "jane o jane","janepass", 30, 3, 2, 1, 1000000, 5);
 --
 -- INSERT INTO USER_PROFILE (
 --   USER_ID,
 --   USER_NM,
 --   PASSWORD,
 --   USER_AGE,
 --   FAMILY_SIZE,
 --   NUM_ADULTS,
 --   NUM_KIDS,
 --   ANNUAL_HOUSEHOLD_INCOME,
 --   SHOP_TRIP_FREQ
 -- )
 -- VALUES ("chu", "cq","chuchu", 30, 3, 2, 1, 1000000, 5);

 --
 --
 -- INSERT INTO USER_GROCERY_RECEIPT (
 --   USER_ID,
 --   RECEIPT_ID,
 --   RECEIPT_UPLOAD_DT,
 --   ITEM_ID,
 --   ITEM_NAME,
 --   ITEM_QTY_PRCH,
 --   ITEM_UNITS,
 --   ITEM_TOTAL_PRICE,
 --   ITEM_CATEGORY,
 -- )
 -- VALUES ("bob", "1234","2017-05-05", 1, "Apple", 5, "oz", 10, "FRUITS");
 -- INSERT INTO USER_GROCERY_RECEIPT (
 --   USER_ID,
 --   RECEIPT_ID,
 --   RECEIPT_UPLOAD_DT,
 --   ITEM_ID,
 --   ITEM_NAME,
 --   ITEM_QTY_PRCH,
 --   ITEM_UNITS,
 --   ITEM_TOTAL_PRICE,
 --   ITEM_CATEGORY,
 -- )
 -- VALUES ("bob", "1234","2017-05-05", 2, "Banana", 2, "oz", 10, "FRUITS");
 -- INSERT INTO USER_GROCERY_RECEIPT (
 --   USER_ID,
 --   RECEIPT_ID,
 --   RECEIPT_UPLOAD_DT,
 --   ITEM_ID,
 --   ITEM_NAME,
 --   ITEM_QTY_PRCH,
 --   ITEM_UNITS,
 --   ITEM_TOTAL_PRICE,
 --   ITEM_CATEGORY,
 -- )
 -- VALUES ("bob", "1234","2017-05-05", 1, "Oranges", 4, "oz", 10, "FRUITS");
 --
