---
title: "Untitled"
author: "Adam Reilly"
date: "February 18, 2018"
output: html_document
---


```{r}
purch0217<- read.csv(file  = "purchases_2_16_full.csv", strip.white=TRUE)
purch0217$category = ifelse(purch0217$category != 'FOW', as.character(purch0217$category), 'FOWL')
```

I am going to create columns for the multipliers for:
1. age (-25% for 70)
2. personal trait (randomized: -25% for 10% of pop, +50% for 10% of pop)
3. income (+- 5% for each standard deviation from mean)
4. household size (+25% for 1, +5% for 2, -5% for 3, -15% for 4, -25% for 5)
5. complete waste (equal to 0.5+0.5 * (per_capita_size-10000)/1000
HOUSEHOLD SIZE, PERSONAL TRAIT, INCOME, AGE

1. Set 25% of the values to 0% waste randomly within each category
2. Setting x% of the values to 100% (x = )
3. 
```{r}
set.seed(1)
purch0217$age_mult = ifelse(purch0217$age == 70, -25, 0)
purch0217$random_number  = runif(537979, min=0, max=100)
purch0217$personal_mult  = ifelse(purch0217$random_number < 10, -25, ifelse((purch0217$random_number>80 & purch0217$random_number <= 90), 25,
                                  ifelse(purch0217$random_number > 90, 50, 0)))
                                         purch0217$income_mult = (purch0217$income - mean(purch0217$income))/sd(purch0217$income)
purch0217$household_mult = ifelse(purch0217$household_count == 1, 25, ifelse(purch0217$household_count == 2, 0, 
                                                                            ifelse(purch0217$household_count == 3, -5,
                                                                            ifelse(purch0217$household_count == 4, -15, - 25))))
purch0217$random_number_ff = runif(537979, min=-10, max=10)
purch0217$random_number_pf = runif(537979, min=-10, max=10)
purch0217$random_number_fv = runif(537979, min=-10, max=10)
purch0217$random_number_pv = runif(537979, min=-10, max=10)
purch0217$random_number_milk = runif(537979, min=-10, max=10)
purch0217$random_number_dairy = runif(537979, min=-10, max=10)
purch0217$random_number_grain = runif(537979, min=-10, max=10)
purch0217$random_number_meat = runif(537979, min=-10, max=10)
purch0217$random_number_fowl = runif(537979, min=-10, max=10)
purch0217$random_number_fish = runif(537979, min=-10, max=10)
purch0217$random_number_nuts = runif(537979, min=-10, max=10)
purch0217$random_number_sugar = runif(537979, min=-10, max=10)
purch0217$random_number_oils = runif(537979, min=-10, max=10)
purch0217$random_number_mix = runif(537979, min=-10, max=10)
purch0217$random_number_alter = runif(537979, min=0, max=100)
purch0217$random_effect = ifelse(purch0217$random_number_alter < 25, 0, 
                                 ifelse(purch0217$random_number > 99.5-(purch0217$per_capita_size-10000)/2000, 100, 1))
purch0217$type_mult = ifelse(purch0217$category == 'FRESH FRUIT', purch0217$random_number_ff, 
                      ifelse(purch0217$category == 'PROCESSED FRUIT', purch0217$random_number_pf, 
                      ifelse(purch0217$category == 'FRESH VEGETABLES', purch0217$random_number_fv,
                      ifelse(purch0217$category == 'PROCESSED VEGETABLES', purch0217$random_number_pv,
                      ifelse(purch0217$category == 'MILK', purch0217$random_number_milk,
                      ifelse(purch0217$category == 'DAIRY', purch0217$random_number_dairy,
                      ifelse(purch0217$category == 'GRAIN', purch0217$random_number_grain,                
                      ifelse(purch0217$category == 'MEAT', purch0217$random_number_meat,
                      ifelse(purch0217$category == 'FOWL', purch0217$random_number_fowl,
                      ifelse(purch0217$category == 'FISH', purch0217$random_number_fish,
                      ifelse(purch0217$category == 'NUTS', purch0217$random_number_nuts,
                      ifelse(purch0217$category == 'SUGAR', purch0217$random_number_sugar,
                      ifelse(purch0217$category == 'OILS', purch0217$random_number_oils, purch0217$random_number_mix)))))))))))))
purch0217$total_mult = purch0217$age_mult + purch0217$personal_mult + purch0217$income_mult + purch0217$household_mult + purch0217$type_mult
purch0217$food_loss_no_alter = purch0217$consumer_loss * (100+purch0217$total_mult)/100
purch0217$food_loss = ifelse(purch0217$random_effect == 0, 0, ifelse(purch0217$random_effect == 100, 100, purch0217$food_loss_no_alter))
                                                        
```
```{r}
write.csv(file="Purchases_2_17.csv", x=purch0217)
```
